### ISSUE TITLE
Country name display

### ISSUE THREAD

**Issue by awmarrs** [HistoryAtState/pocom#5]
@joewiz : it is not clear to me (although I'm sure that we've discussed) why some country names are still displaying on POCOM pages. Here are the examples which @seckroth pointed out in her review:

https://history.state.gov/departmenthistory/people/chiefsofmission/albania ("Albania" appears after every position title through 1939)

https://history.state.gov/departmenthistory/people/chiefsofmission/antigua-barbuda ("Antigua and Barbuda" displays after every position title)

https://history.state.gov/departmenthistory/people/chiefsofmission/czechoslovakia ("Czechoslovakia" displays after every position title)

https://history.state.gov/departmenthistory/people/chiefsofmission/korea ("Korea" displays from 183 to 1905)

https://history.state.gov/departmenthistory/people/chiefsofmission/micronesia ("Micronesia, Federated States of" appears with every entry)

https://history.state.gov/departmenthistory/people/chiefsofmission/two-sicilies ("Kingdom of the Two Sicilies" appears with every entry)

https://history.state.gov/departmenthistory/people/chiefsofmission/vietnam-south ("State of Vietnam" appears from 1950 to 1954, and "South Vietnam" after that)

https://history.state.gov/departmenthistory/people/chiefsofmission/yugoslavia (nothing appears in the first entry, then "Yugoslavia" from 1926 to 1946, and "Socialist Federal Republic of Yugoslavia" after that)

Is something going on here, or does this need to await the complete country names review?

**Comment by joewiz** [comment]
This happens when we provide a `<contemporary-territory-id>` value from the `gsh/data/territories` collection rather than the `gsh/data/countries-old` collection. The idea was to begin using historical country names where the appointment was not to the state as it is known today. The logic in play here is as follows (and can be found at https://github.com/HistoryAtState/hsg-shell/blob/master/modules/pocom-html.xqm#L352):

1. If the `<contemporary-territory-id>` is different than the country mission's root `country-mission/territory-id` element, then we look up the name of the territory in `gsh/data/territories` and insert its short form name in parentheses after the position name.
2. If it's the same as the country mission's ID, then we just list the position name without naming the country.

So the key to what you're seeing is that the `contemporary-territory-id` is different than the `country-mission/territory-id`. To eliminate parenthetical short form names, the `contemporary-territory-id` would have to be changed to the value of the `country-mission/territory-id`. 

Once the country names review is done, we could certainly use that data more broadly for the `contemporary-territory-id` fields.

If the result of the rules above is confusing, we can certainly change it.

Does this answer your questions?

**Comment by joewiz** [comment]
(Correction to no. 1 above: struck "in parentheses".)

**Comment by awmarrs** [comment]
Joe, I'm not sure I really understand what is going on here, maybe better to talk in person, but in any event I'm happy to shelve this comment until the country names review is done because we'll be making some significant changes throughout this section, I would wager. Thanks!

**Comment by joewiz** [comment]
Okay, sure. For reference, let's take Albania:

> <img width="616" alt="screen shot 2016-11-28 at 10 20 01 am" src="https://cloud.githubusercontent.com/assets/59118/20673730/419fade8-b554-11e6-857e-f5f22a7c24a7.png">

The source data for this entry comes from https://github.com/HistoryAtState/pocom/blob/master/missions-countries/albania.xml:

```xml
<country-mission>
    <territory-id>albania</territory-id>
    <chiefs>
        <chief>
            <id>al-1922-gran-01</id>
            <person-id>grant-smith-ulysses</person-id>
            <role-title-id>envoy-extraordinary-minister-plenipotentiary</role-title-id>
            <contemporary-territory-id>albania-1946</contemporary-territory-id>
```

Since "albania-1946" (from Grant-Smith's record's `<contemporary-territory-id>`) is different from the country mission's `<territory-id>`, "albania," the short form name from https://github.com/joewiz/gsh/blob/master/data/territories/albania-1946.xml, namely, "Albania," is shown after the position name. 

In contrast, the post-1991 entries look like this:

> <img width="608" alt="screen shot 2016-11-28 at 10 23 51 am" src="https://cloud.githubusercontent.com/assets/59118/20674015/438c8e22-b555-11e6-9afc-ab8e5d00cb23.png">

The source (https://github.com/HistoryAtState/pocom/blob/master/missions-countries/albania.xml#L154-L158):

```xml
<chief>
    <id>al-1991-hill-01</id>
    <person-id>hill-christopher-robert</person-id>
    <role-title-id>charge-daffaires-ad-interim</role-title-id>
    <contemporary-territory-id>albania</contemporary-territory-id>
```

Since this record's `<contemporary-territory-id>`, "albania," is identical to the country mission's `<territory-id>`, nothing is appended to the position title.

Obviously the Albania example isn't the most compelling use of the historical country names database, but I hope this clarifies my explanation above.

**Comment by awmarrs** [comment]
Joe -- actually, this explanation is terrific, because it is why I was so confused. Albania's short form name hasn't changed -- it was Albania in 1922, and it is Albania today. That's why it was unclear to me why the name was popping up for Grant-Smith, but no other entries.

So, I guess I can understand why we would want names to display under certain circumstances, and I'm also aware that there are a ton of additional changes that will need to be made (Persia/Iran, Siam/Thailand, etc etc). But in my mind, Albania, Federated States of Micronesia, Antigua and Barbuda, and Yugoslavia didn't fit into that category, since their short form names have remained constant. That, I think, is the source of my confusion.

**Comment by joewiz** [comment]
Great, I'm glad the explanation makes sense. Once we've got a complete set of reviewed country names for one of the examples here, let's look at ways to make the presentation clearer.
